// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webshop.Data;

namespace Webshop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220413104428_seed test orders")]
    partial class seedtestorders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "86efe060-a6bf-470e-ae43-3a69c0ce1758",
                            ConcurrencyStamp = "09159eaa-7096-4e39-889f-9cd023fa806c",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "1259de13-a55d-4ba4-9cc3-bbe293dc6d07",
                            ConcurrencyStamp = "6f8841ce-7c05-457d-bdd5-ca344cc85d94",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "0ca0f471-d686-4f5e-85a1-d0e87a995d70",
                            RoleId = "86efe060-a6bf-470e-ae43-3a69c0ce1758"
                        },
                        new
                        {
                            UserId = "79cb9168-f470-4620-b861-edc081705d94",
                            RoleId = "1259de13-a55d-4ba4-9cc3-bbe293dc6d07"
                        },
                        new
                        {
                            UserId = "cd46f162-dd90-426d-8fe0-20944d5df397",
                            RoleId = "1259de13-a55d-4ba4-9cc3-bbe293dc6d07"
                        },
                        new
                        {
                            UserId = "6671a692-f7ef-4cd7-9520-ff50c7c6a283",
                            RoleId = "1259de13-a55d-4ba4-9cc3-bbe293dc6d07"
                        },
                        new
                        {
                            UserId = "54a7b7aa-108e-4c64-8b84-8fbb92615e52",
                            RoleId = "1259de13-a55d-4ba4-9cc3-bbe293dc6d07"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Webshop.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "0ca0f471-d686-4f5e-85a1-d0e87a995d70",
                            AccessFailedCount = 0,
                            Address = "Adminvägen 1",
                            City = "Admin city",
                            ConcurrencyStamp = "28c57389-ee2f-46e8-9f32-584070647b33",
                            Country = "Admin country",
                            Email = "admin@admin.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Adminsson",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBdH4t3ldRZrYCusr85NREilxT6gfFgV1zKQhvuG0OGdXsxSg0UwXCfwlVGRYOJuYQ==",
                            PhoneNumber = "123456578",
                            PhoneNumberConfirmed = false,
                            PostalCode = "12345",
                            SecurityStamp = "caae5b8e-bd79-4dee-84ae-e9d89e512c31",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = "79cb9168-f470-4620-b861-edc081705d94",
                            AccessFailedCount = 0,
                            Address = "Kanelgatan 3",
                            City = "Visby",
                            ConcurrencyStamp = "341fba9e-d583-4163-aa77-0fd06a41b441",
                            Country = "Sweden",
                            Email = "customer1@seeduser.com",
                            EmailConfirmed = false,
                            FirstName = "Arne",
                            LastName = "Karat",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER1@SEEDUSER.COM",
                            NormalizedUserName = "CUSTOMER1@SEEDUSER.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKqrh1NVnJxdkZ3/83MXaT/dG30WlJniOt2r4Ghibs09CLqHWlh3T9aVuoj9tGiUbw==",
                            PhoneNumber = "043016624",
                            PhoneNumberConfirmed = false,
                            PostalCode = "23445",
                            SecurityStamp = "2b497417-8561-478d-80eb-fa08880bfc3c",
                            TwoFactorEnabled = false,
                            UserName = "customer1@seeduser.com"
                        },
                        new
                        {
                            Id = "cd46f162-dd90-426d-8fe0-20944d5df397",
                            AccessFailedCount = 0,
                            Address = "Rimbo torg 1",
                            City = "Skövde",
                            ConcurrencyStamp = "973414a1-736f-405d-8cd8-7e54ee0adde9",
                            Country = "Sweden",
                            Email = "customer2@seeduser.com",
                            EmailConfirmed = false,
                            FirstName = "Kenneth",
                            LastName = "Svenzon",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER2@SEEDUSER.COM",
                            NormalizedUserName = "CUSTOMER2@SEEDUSER.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFZxSgDn0YdkSdxYmgKhebvfjOOtmRF3gQcWR/3kdsqr1rEiaLMMIa/8LH8fQ81k5Q==",
                            PhoneNumber = "0721453456",
                            PhoneNumberConfirmed = false,
                            PostalCode = "44565",
                            SecurityStamp = "bbcd78d5-3024-43bd-80ff-83ac013c4e1a",
                            TwoFactorEnabled = false,
                            UserName = "customer2@seeduser.com"
                        },
                        new
                        {
                            Id = "6671a692-f7ef-4cd7-9520-ff50c7c6a283",
                            AccessFailedCount = 0,
                            Address = "Kungsgatan 4",
                            City = "Arboga",
                            ConcurrencyStamp = "c0ae6bef-1957-4dee-9127-a978f6876826",
                            Country = "Sweden",
                            Email = "customer3@seeduser.com",
                            EmailConfirmed = false,
                            FirstName = "Angela",
                            LastName = "Melodi",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER3@SEEDUSER.COM",
                            NormalizedUserName = "CUSTOMER3@SEEDUSER.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENZpKmKqelaZJorixJEG7ni0/74Yen4pkmbIsQScZPvRk/Wuv+oiqzP6gU+W2LDxJA==",
                            PhoneNumber = "0771242424",
                            PhoneNumberConfirmed = false,
                            PostalCode = "32344",
                            SecurityStamp = "cd0ec23a-d1dd-41d1-ad8e-4b0a463486dc",
                            TwoFactorEnabled = false,
                            UserName = "customer3@seeduser.com"
                        },
                        new
                        {
                            Id = "54a7b7aa-108e-4c64-8b84-8fbb92615e52",
                            AccessFailedCount = 0,
                            Address = "Royal Carnac Hotel 1",
                            City = "Cairo",
                            ConcurrencyStamp = "3f84c690-4716-452c-94ee-9aa196afb06e",
                            Country = "Egypt",
                            Email = "seeduser@seeduser.com",
                            EmailConfirmed = false,
                            FirstName = "Kaj",
                            LastName = "Fridell",
                            LockoutEnabled = false,
                            NormalizedEmail = "SEEDUSER@SEEDUSER.COM",
                            NormalizedUserName = "SEEDUSER@SEEDUSER.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIQXBNieiFYp+dNtkO1NLZpI1M8cUKTGy76gJaKqmN4DUY6N/6jxSJcHPGvtKMs0gA==",
                            PhoneNumber = "031184698",
                            PhoneNumberConfirmed = false,
                            PostalCode = "33467",
                            SecurityStamp = "da000ee7-948b-4525-ac56-6ccdd4d0821d",
                            TwoFactorEnabled = false,
                            UserName = "seeduser@seeduser.com"
                        });
                });

            modelBuilder.Entity("Webshop.Models.CartContent", b =>
                {
                    b.Property<int>("CartContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCost")
                        .HasColumnType("int");

                    b.HasKey("CartContentId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartContents");
                });

            modelBuilder.Entity("Webshop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CategoryName = "Chocolate"
                        },
                        new
                        {
                            Id = 102,
                            CategoryName = "Frosted"
                        },
                        new
                        {
                            Id = 103,
                            CategoryName = "Gluten free"
                        },
                        new
                        {
                            Id = 104,
                            CategoryName = "Berries and fruits"
                        });
                });

            modelBuilder.Entity("Webshop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kanelgatan 3",
                            City = "Visby",
                            Country = "Sweden",
                            Email = "bling@gmail.com",
                            FirstName = "Arne",
                            LastName = "Karat",
                            PhoneNumber = "043016624",
                            PostalCode = "23445"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Rimbo torg 1",
                            City = "Skövde",
                            Country = "Sweden",
                            Email = "stekarn@gmail.com",
                            FirstName = "Kenneth",
                            LastName = "Svenzon",
                            PhoneNumber = "0721453456",
                            PostalCode = "44565"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kungsgatan 4",
                            City = "Arboga",
                            Country = "Sweden",
                            Email = "lucky@hotmail.com",
                            FirstName = "Angela",
                            LastName = "Melodi",
                            PhoneNumber = "0771242424",
                            PostalCode = "32344"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Royal Carnac Hotel 1",
                            City = "Cairo",
                            Country = "Egypt",
                            Email = "kafr@egypt.gov",
                            FirstName = "Kaj",
                            LastName = "Fridell",
                            PhoneNumber = "031184698",
                            PostalCode = "33467"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Vedgatan 3",
                            City = "Oslo",
                            Country = "Norway",
                            Email = "tavlan@gmail.com",
                            FirstName = "Molly",
                            LastName = "Sundkvist",
                            PhoneNumber = "0443346723",
                            PostalCode = "46723"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Gatgatan 2",
                            City = "Göteborg",
                            Country = "Sweden",
                            Email = "test@gmail.com",
                            FirstName = "Jan",
                            LastName = "Andersson",
                            PhoneNumber = "04422723",
                            PostalCode = "46723"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Avenyn 1",
                            City = "Berlin",
                            Country = "Germany",
                            Email = "raj@goteborg.se",
                            FirstName = "Sofia",
                            LastName = "Bosch",
                            PhoneNumber = "0543768798",
                            PostalCode = "67823"
                        });
                });

            modelBuilder.Entity("Webshop.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CustomerId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<int>("TotalCost")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerId1");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = "79cb9168-f470-4620-b861-edc081705d94",
                            OrderDate = new DateTime(2022, 4, 13, 12, 44, 27, 688, DateTimeKind.Local).AddTicks(3270),
                            Paid = true,
                            TotalCost = 87
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = "cd46f162-dd90-426d-8fe0-20944d5df397",
                            OrderDate = new DateTime(2022, 4, 13, 12, 44, 27, 690, DateTimeKind.Local).AddTicks(5856),
                            Paid = true,
                            TotalCost = 44
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = "cd46f162-dd90-426d-8fe0-20944d5df397",
                            OrderDate = new DateTime(2022, 4, 13, 12, 44, 27, 690, DateTimeKind.Local).AddTicks(5936),
                            Paid = true,
                            TotalCost = 257
                        });
                });

            modelBuilder.Entity("Webshop.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            OrderId = 1,
                            Price = 29,
                            ProductId = 1001,
                            ProductName = "Chocolate Dream",
                            Quantity = 3
                        },
                        new
                        {
                            OrderDetailId = 2,
                            OrderId = 2,
                            Price = 22,
                            ProductId = 1002,
                            ProductName = "Pink surprise",
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailId = 3,
                            OrderId = 3,
                            Price = 34,
                            ProductId = 1003,
                            ProductName = "Plain delight",
                            Quantity = 5
                        },
                        new
                        {
                            OrderDetailId = 4,
                            OrderId = 3,
                            Price = 29,
                            ProductId = 1001,
                            ProductName = "Chocolate Dream",
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Webshop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductImageId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CategoryId = 101,
                            Description = "A delicious chocolate cupcake with belgian chocolate",
                            Name = "Chocolate Dream",
                            Price = 29,
                            ProductImageId = 1
                        },
                        new
                        {
                            Id = 1002,
                            CategoryId = 102,
                            Description = "A frosted strawberry cupcake, filled with strawberry jam",
                            Name = "Pink surprise",
                            Price = 22
                        },
                        new
                        {
                            Id = 1003,
                            CategoryId = 103,
                            Description = "A gluten free cupcake packed with flavor",
                            Name = "Plain delight",
                            Price = 34
                        },
                        new
                        {
                            Id = 1004,
                            CategoryId = 104,
                            Description = "Filled with peanut butter and topped with delicious peanut frosting.",
                            Name = "Peanut butter cup-cake",
                            Price = 34
                        },
                        new
                        {
                            Id = 1005,
                            CategoryId = 101,
                            Description = "This is the cupcake for you if you like all things Nutella.",
                            Name = "Nutella mountain",
                            Price = 34
                        },
                        new
                        {
                            Id = 1006,
                            CategoryId = 101,
                            Description = "A cupcake made to look like a giant M&M.",
                            Name = "M&M don't sue us",
                            Price = 34
                        },
                        new
                        {
                            Id = 1007,
                            CategoryId = 104,
                            Description = "Not the tea, instead a cupcake with every kind of berry.",
                            Name = "Forest fruit",
                            Price = 34
                        },
                        new
                        {
                            Id = 1008,
                            CategoryId = 101,
                            Description = "Oreo cookie on top as well as batter and frosting made from oreo's.",
                            Name = "Oreo supreme",
                            Price = 34
                        },
                        new
                        {
                            Id = 1009,
                            CategoryId = 104,
                            Description = "If you like something with a fresher taste, this cupcake is for you.",
                            Name = "Lemon",
                            Price = 34
                        },
                        new
                        {
                            Id = 1010,
                            CategoryId = 104,
                            Description = "Every taste of the fruit rainbow you can imagine.",
                            Name = "Taste the rainbow",
                            Price = 34
                        });
                });

            modelBuilder.Entity("Webshop.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Webshop.Models.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            ImageName = "chokladbild.jpg",
                            ImageThumbName = "chokladbildth.jpg",
                            ImageTitle = "Chocolate Dream"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Webshop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Webshop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Webshop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webshop.Models.CartContent", b =>
                {
                    b.HasOne("Webshop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Webshop.Models.Customer", b =>
                {
                    b.HasOne("Webshop.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Customer")
                        .HasForeignKey("Webshop.Models.Customer", "CustomerId");
                });

            modelBuilder.Entity("Webshop.Models.Order", b =>
                {
                    b.HasOne("Webshop.Models.ApplicationUser", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Webshop.Models.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId1");
                });

            modelBuilder.Entity("Webshop.Models.OrderDetail", b =>
                {
                    b.HasOne("Webshop.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webshop.Models.Product", b =>
                {
                    b.HasOne("Webshop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Webshop.Models.ProductImage", "ProductImage")
                        .WithMany("Products")
                        .HasForeignKey("ProductImageId");
                });

            modelBuilder.Entity("Webshop.Models.ProductCategory", b =>
                {
                    b.HasOne("Webshop.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
